server:
  port: 9420

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamic_gateway?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: static_route
          uri: https://top.baidu.com
          predicates:
            - Path=/board
    refresh:
      interval: 5s
