server:
  port: 9420

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamic_gateway?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver
